services:
  identidock:
    build: .
    ports:
     - "5000:9090"
    environment:
      ENV: DEV
    depends_on: [dnmonster, redis]

  dnmonster:
    image: amouat/dnmonster:1.0
  redis:
    image: redis:alpine3.18
